version: '3.8'
services:
  dockflare:
    image: alplat/dockflare:stable  # alplat/dockflare:unstable docker tag for beta versions
    # build: ./dockflare  # Uncomment to build from source instead
    container_name: dockflare
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Required to monitor Docker events
      - dockflare_data:/app/data  # Persistent storage for state
    networks:
      - cloudflare-net  # Network for communication with other containers
    environment:
      - STATE_FILE_PATH=/app/data/state.json
      - TZ=Europe/Zurich  # Set your timezone here
    #labels: # Optional
    #- dockflare.enable=true
    #- dockflare.hostname=dockflare.yourdomain.tld
    #- dockflare.service=http://dockflare:5000  
volumes:
  dockflare_data:
networks:
  cloudflare-net:
   name: cloudflare-net