version: '3.8'
services:
  cloudflare-tunnel-manager:
    build: . # for building local docker image
    container_name: dockflare
    # image: alplat/dockflare:stable # The pre-built Docker image (`alplat/dockflare:stable`) is currently only available for `x86_64` / `amd64` architectures.
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dockflare_data:/app/data
    networks:
      - cloudflare-net
    environment:
      - STATE_FILE_PATH=/app/data/state.json
      - TZ=Europe/Zurich # Set the timezone to Zurich
      # External cloudflared Configuration:
      # Enable this to use an existing cloudflared instance instead of creating one
      # Only the tunnel ID is needed - you don't need to specify the container name
      # - USE_EXTERNAL_CLOUDFLARED=true
      # - EXTERNAL_TUNNEL_ID=your-external-tunnel-id
volumes:
  dockflare_data:
networks:
  cloudflare-net:
    name: cloudflare-net