version: '3.8'
services:
  cloudflare-tunnel-manager:
    build: . # for building local docker image
    container_name: dockflare
    # image: alplat/dockflare:stable # The pre-built Docker image (`alplat/dockflare:stable`) is currently only available for `x86_64` / `amd64` architectures.
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dockflare_data:/app/data
    networks:
      - cloudflare-net
    environment:
      - STATE_FILE_PATH=/app/data/state.json
      - TZ=Europe/Zurich # Set the timezone to Zurich
      - EXTERNAL_HOSTNAME=https://dockflare.example.com # Optional: Set the external hostname for reverse proxy
      - BASE_URL=/ # Optional: Set the base URL if the app is served under a subpath
volumes:
  dockflare_data:
networks:
  cloudflare-net:
    name: cloudflare-net